version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  
  rp:
    image: "nginx"
    volumes:
      - ./nginxconf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"